In [1]:
import numpy as np
import pandas as pd

dfs = pd.read_csv("https://raw.githubusercontent.com/notnsas/cautious-eureka/refs/heads/main/dataset/konbert-output-00ddbb46.csv")
dfs

Timur  Barat  Selatan
0    135    175      180
1    155    180      160
2    150    195      165

In [8]:
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

# Example dataset
data = pd.DataFrame({
    'score': [135, 155, 150, 175, 180, 195, 180, 160, 165],
    'teaching_method': ['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C'],
    'study_hours': ['Low', 'Medium', 'High', 'Low', 'Medium', 'High', 'Low', 'Medium', 'High']
})

# Two-way ANOVA without interaction
model = smf.ols('score ~ C(teaching_method) + C(study_hours)', data=data).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

print(anova_table)


                         sum_sq   df         F    PR(>F)
C(teaching_method)  2038.888889  2.0  7.057692  0.048756
C(study_hours)        72.222222  2.0  0.250000  0.790123
Residual             577.777778  4.0       NaN       NaN


In [2]:
class TwoWay:
  def __init__(self, df):
    self.df = df.to_numpy()

  def hitung(self):
    df = self.df
    xij = np.sum(np.sum(df**2))
    t_2 = np.sum(np.sum(df, axis=1))**2
    kb = df.shape[0] * df.shape[1]

    jkt = xij - t_2 / kb
    print(f"JKT = {xij} - ({t_2}/{kb}) = {jkt}")

    ti_sum = np.sum(np.sum(df, axis=1)**2)
    k = df.shape[1]

    jkb = ti_sum / k - t_2 / kb
    print(f"JKB = ({ti_sum} / {k}) - ({t_2} / {kb}) = {jkb}")

    tj_sum = np.sum(np.sum(df, axis=0)**2)
    # tj_sum = 752125
    b = df.shape[0]

    jkk = (tj_sum / b) - (t_2 / kb)
    print(f"JKK = ({tj_sum} / {b}) - ({t_2} / {kb}) = {jkk}")

    jke = jkt - (jkb + jkk)
    print(f"JKE = {jkt} - ({jkb} + {jkk}) = {jke}")


    db = b - 1
    dk = k - 1
    de = (k - 1)*(b - 1)
    s1_2 = jkb / db
    print(f"s1_2 = {jkb} / {db} = {s1_2}")

    s2_2 = jkk / dk
    print(f"s2_2 = {jkk} / {dk} = {s2_2}")

    s3_2 = jke / de
    print(f"s3_2 = {jke} / {de} = {s3_2}")

    f1 = s1_2 / s3_2
    print(f"f1 = {s1_2} / {s3_2} = {f1}")

    f2 = s2_2 / s3_2
    print(f"f2 = {s2_2} / {s3_2} = {f2}")


In [ ]:
df = dfs.to_numpy()
np.sum(np.sum(df**2))

np.int64(251025)

In [ ]:
505*505

255025

In [3]:
contoh = TwoWay(dfs)
contoh.hitung()

JKT = 251025 - (2235025/9) = 2688.888888888876
JKB = (745225 / 3) - (2235025 / 9) = 72.22222222221899
JKK = (751125 / 3) - (2235025 / 9) = 2038.888888888876
JKE = 2688.888888888876 - (72.22222222221899 + 2038.888888888876) = 577.777777777781
s1_2 = 72.22222222221899 / 2 = 36.111111111109494
s2_2 = 2038.888888888876 / 2 = 1019.444444444438
s3_2 = 577.777777777781 / 4 = 144.44444444444525
f1 = 36.111111111109494 / 144.44444444444525 = 0.2499999999999874
f2 = 1019.444444444438 / 144.44444444444525 = 7.057692307692223


In [ ]:
lat = pd.read_csv("/content/konbert-output-efe0f23a.csv")
latihan = TwoWay(lat)
latihan.hitung()

JKT = 6725 - (71289/12) = 784.25
JKB = (17855 / 3) - (71289 / 12) = 10.91666666666697
JKK = (24309 / 4) - (71289 / 12) = 136.5
JKE = 784.25 - (10.91666666666697 + 136.5) = 636.833333333333
s1_2 = 10.91666666666697 / 3 = 3.63888888888899
s2_2 = 136.5 / 2 = 68.25
s3_2 = 636.833333333333 / 6 = 106.13888888888884
f1 = 3.63888888888899 / 106.13888888888884 = 0.034284218790893405
f2 = 68.25 / 106.13888888888884 = 0.6430253860246011


In [ ]:
import pandas as pd
from io import StringIO

s = """
Stasiun kerja I,Stasiun kerja II,Stasiun kerja III,Jumlah (Ti)
76,72,71,219
63,63,54,180
66,65,62,193
83,78,76,237
74,69,65,208
53,49,50,152
"""
s = s.strip()

soal = pd.read_csv(StringIO(s), sep=',')
soal = soal.drop("Jumlah (Ti)", axis=1)
soal_lat = TwoWay(soal)
soal_lat.hitung()

JKT = 80201 - (1413721/18) = 1660.944444444438
JKB = (240147 / 3) - (1413721 / 18) = 1508.944444444438
JKK = (471925 / 6) - (1413721 / 18) = 114.1111111111095
JKE = 1660.944444444438 - (1508.944444444438 + 114.1111111111095) = 37.888888888890506
s1_2 = 1508.944444444438 / 5 = 301.7888888888876
s2_2 = 114.1111111111095 / 2 = 57.05555555555475
s3_2 = 37.888888888890506 / 10 = 3.7888888888890504
f1 = 301.7888888888876 / 3.7888888888890504 = 79.65102639295814
f2 = 57.05555555555475 / 3.7888888888890504 = 15.058651026392107


In [ ]:
soal

Stasiun kerja I  Stasiun kerja II  Stasiun kerja III
0               76                72                 71
1               63                63                 54
2               66                65                 62
3               83                78                 76
4               74                69                 65
5               53                49                 50

In [ ]:
import pandas as pd
from io import StringIO

s = """
V1,V2,V3,V4
60,59,70,55
58,62,63,61
75,61,68,70
71,54,73,69
57,58,53,62
41,61,59,53
"""
s = s.strip()

dfis = pd.read_csv(StringIO(s), sep=',')
dfi = dfis.to_numpy()

In [ ]:
class TwoWayInt:
  def __init__(self, df, n):
    self.df = df.to_numpy()
    self.n = n

  def hitung(self):
    df = self.df
    n = self.n
    b= df.shape[0] / n
    k = df.shape[1]
    xijc = np.sum(df**2)
    t_2 = 0
    for i in range(0, df.shape[0], n):
      t_2 += np.sum(df[i:i+n])
      # print(df[i:i+n])
      # print()
    t_2 = t_2**2
    bkn = n * df.shape[0] / n * df.shape[1]

    jkt = xijc - (t_2 / bkn)
    print(f"jkt = {xijc} - ({t_2} / {bkn}) = {jkt}")


    ti_2 = 0
    for i in range(0, df.shape[0], n):
      ti_2 += (np.sum(df[i:i+n])**2)
      # print(df[i:i+n])
      # print()
    kn = df.shape[1] * n

    jkb = (ti_2 / kn) - (t_2 / bkn)
    print(f"jkb = ({ti_2} / {kn}) - ({t_2} / {bkn}) = {jkb}")


    tj_2 = np.sum(np.sum(df, axis=0)**2)
    bn = b * n

    jkk = (tj_2 / bn) - (t_2 / bkn)
    print(f"jkk = ({tj_2} / {bn}) - ({t_2} / {bkn}) = {jkk}")


    tij = 0
    for i in range(0, df.shape[0], n):
      tij += np.sum((np.sum(df[i:i+n], axis=0))**2)
      print(((np.sum(df[i:i+n], axis=0))**2))
      # print()

    jki = (tij / n) - (ti_2 / kn) - (tj_2 / bn) + (t_2 / bkn)
    print(f"jki = ({tij} / {n}) - ({ti_2} / {kn}) - ({tj_2} / {bn}) + ({t_2} / {bkn}) = {jki}")


    jke = jkt - jkb - jkk - jki
    print(f"jke = {jkt} - {jkb} - {jkk} - {jki} = {jke}")


    db = b - 1
    s1 = jkb / db
    print(f"s1 = {jkb} / {db} = {s1}")

    dk = k - 1
    s2 = jkk / dk
    print(f"s2 = {jkk} / {dk} = {s2}")

    di = (b - 1) * (k - 1)
    s3 = jki / di
    print(f"s3 = {jki} / {di} = {s3}")

    de = b*k*(n -1)
    s4 = jke / de
    print(f"s4 = {jke} / {de} = {s4}")

    f1 = s1 / s4
    print(f"f1 = {s1} / {s4} = {f1}")

    f2 = s2 / s4
    print(f"f2 = {s2} / {s4} = {f2}")

    f3 = s3 / s4
    print(f"f3 = {s3} / {s4} = {f3}")


In [ ]:
t_2 = 0
for i in range(0, dfi.shape[0], 2):
  t_2 +=np.sum((np.sum(dfi[i:i+2], axis=0))**2)
  print()
  # t_2 += np.sum(dfi[i:i+2])
print(t_2)
np.sum(df**2)




182987


np.int64(251025)

In [ ]:
np.sum(dfi, axis=0)

array([362, 355, 386, 370])

In [ ]:
cont_int = TwoWayInt(dfis, 2)
cont_int.hitung()

jkt = 91779 - (2169729 / 24.0) = 1373.625
jkb = (727961 / 8) - (2169729 / 24.0) = 589.75
jkk = (542965 / 6.0) - (2169729 / 24.0) = 88.79166666667152
[13924 14641 17689 13456]
[21316 13225 19881 19321]
[ 9604 14161 12544 13225]
jki = (182987 / 2) - (727961 / 8) - (542965 / 6.0) + (2169729 / 24.0) = 409.5833333333285
jke = 1373.625 - 589.75 - 88.79166666667152 - 409.5833333333285 = 285.5
s1 = 589.75 / 2.0 = 294.875
s2 = 88.79166666667152 / 3 = 29.597222222223838
s3 = 409.5833333333285 / 6.0 = 68.26388888888808
s4 = 285.5 / 12.0 = 23.791666666666668
f1 = 294.875 / 23.791666666666668 = 12.394045534150612
f2 = 29.597222222223838 / 23.791666666666668 = 1.2440163455925957
f3 = 68.26388888888808 / 23.791666666666668 = 2.8692352597781325


In [ ]:
542965 / 6.0

90494.16666666667

In [ ]:

import pandas as pd
from io import StringIO

s = """
P1,P2,P3
39,35,40
37,39,41
35,43,42
37,38,41
38,38,45
37,36,42
40,40,41
40,41,44
35,42,40
"""
s = s.strip()

df_lat = pd.read_csv(StringIO(s), sep=',')
# df_lat = dfis.to_numpy()
df_lat

P1  P2  P3
0  39  35  40
1  37  39  41
2  35  43  42
3  37  38  41
4  38  38  45
5  37  36  42
6  40  40  41
7  40  41  44
8  35  42  40

In [ ]:
lat_int = TwoWayInt(df_lat, 3)
lat_int.hitung()

jkt = 42278 - (1136356 / 27.0) = 190.74074074073724
jkb = (378874 / 9) - (1136356 / 27.0) = 9.851851851846732
jkk = (379524 / 9.0) - (1136356 / 27.0) = 82.074074074073
[12321 13689 15129]
[12544 12544 16384]
[13225 15129 15625]
jki = (126590 / 3) - (378874 / 9) - (379524 / 9.0) + (1136356 / 27.0) = 17.48148148148175
jke = 190.74074074073724 - 9.851851851846732 - 82.074074074073 - 17.48148148148175 = 81.33333333333576
s1 = 9.851851851846732 / 2.0 = 4.925925925923366
s2 = 82.074074074073 / 2 = 41.0370370370365
s3 = 17.48148148148175 / 4.0 = 4.370370370370438
s4 = 81.33333333333576 / 18.0 = 4.518518518518653
f1 = 4.925925925923366 / 4.518518518518653 = 1.0901639344256304
f2 = 41.0370370370365 / 4.518518518518653 = 9.081967213114364
f3 = 4.370370370370438 / 4.518518518518653 = 0.9672131147540844


In [ ]:
np.sum(np.sum(df_lat))**2

/usr/local/lib/python3.11/dist-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


np.int64(1136356)

In [ ]:
df_lat

P1  P2  P3
0  39  35  40
1  37  39  41
2  35  43  42
3  37  38  41
4  38  38  45
5  37  36  42
6  40  40  41
7  40  41  44
8  35  42  40

In [ ]:
import numpy as np

# Define the three matrices
arr1 = np.array([[39, 35, 40],
                 [37, 39, 41],
                 [35, 43, 42]])

arr2 = np.array([[37, 38, 41],
                 [38, 38, 45],
                 [37, 36, 42]])

arr3 = np.array([[40, 40, 41],
                 [40, 41, 44],
                 [35, 42, 40]])

# Sum of all elements in each array
sum1 = arr1.sum()
sum2 = arr2.sum()
sum3 = arr3.sum()

# Add all the sums together
total_sum = sum1**2 + sum2**2 + sum3**2

print("Total sum:", total_sum)


Total sum: 378874
