<a href="https://colab.research.google.com/github/notnsas/cautious-eureka/blob/main/statistika/ANOVA_ONE_WAY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/konbert-output-b61cb727.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/konbert-output-b61cb727.csv'

In [ ]:
np.sum(df, axis=0).to_numpy()**2 / df.count().to_numpy()

array([20352.2, 19845. , 16245. , 14045. ])

In [ ]:
np.nansum(np.sum(df, axis=0)**2 / df.count().to_numpy())

70487.2

In [ ]:
np.nansum(df, axis=0)

array([319, 315, 285, 265])

In [ ]:
np.sum(np.sum(df, axis=0).to_numpy()**2 / df.count().to_numpy())

70487.2

In [ ]:
np.sum(np.sum(df.to_numpy()))

1184

In [17]:
class AnovaOneWay:
  def __init__(self, df):
    self.df = df
    self.data = df.to_numpy()
    self.df_1 = df.shape[1] - 1
    self.df_2 = np.sum(self.df.count()) - df.shape[1]

  def jkp(self):
    sum_tj_nj = np.nansum(np.nansum(self.df, axis=0)**2 / self.df.count().to_numpy())
    t_n = np.nansum(np.nansum(self.df.to_numpy()))**2 / (np.count_nonzero(~np.isnan(self.data)))
    jkp = sum_tj_nj - t_n
    print(f"jkp = {sum_tj_nj} - {t_n} = {jkp}")
    return jkp

  def jkt(self):
    x_i_j = np.nansum(self.data**2)
    t_n = np.nansum(np.nansum(self.df.to_numpy()))**2 / (np.count_nonzero(~np.isnan(self.data)))
    jkt = x_i_j - t_n
    print(f"jkt = {x_i_j} - {t_n} = {jkt}")
    return jkt

  def jkg(self):
    jkg = self.jkt() - self.jkp()
    print(f"jkg = {self.jkt()} - {self.jkp()} = {jkg}")
    return jkg

  def rjkp(self):
    jkp = self.jkp()
    k = self.df.shape[1]
    rjkp = jkp / (k - 1)
    print(f"jkp : {jkp}")
    print(f"k : {jkp}")
    print(f"rjkp = {jkp} / ({k} - 1) = {rjkp}")
    return rjkp

  def rjkg(self):
    jkg = self.jkg()
    N = np.sum(self.df.count())
    k =self.df.shape[1]
    rjkg = jkg / (N - k)
    print(f"rjkg = {jkg} / ({N} - {k}) = {rjkg}")
    return rjkg

  def f_hitung(self):
    rjkp = self.rjkp()
    rjkg = self.rjkg()
    f_hitung = rjkp / rjkg
    print(f"f_hitung = {rjkp} / {rjkg} = {f_hitung}")
    return f_hitung


In [18]:
satu = AnovaOneWay(df)

NameError: name 'df' is not defined

In [19]:
satu.jkp()

NameError: name 'satu' is not defined

In [20]:
satu.jkt()

NameError: name 'satu' is not defined

In [21]:
satu.rjkp()

NameError: name 'satu' is not defined

In [22]:
satu.rjkg()

NameError: name 'satu' is not defined

In [ ]:
satu.f_hitung()

jkp = 70487.2 - 70092.8 = 394.3999999999942
jkp : 394.3999999999942
k : 394.3999999999942
rjkp = 394.3999999999942 / (4 - 1) = 131.46666666666474
jkt = 70630 - 70092.8 = 537.1999999999971
jkp = 70487.2 - 70092.8 = 394.3999999999942
jkt = 70630 - 70092.8 = 537.1999999999971
jkp = 70487.2 - 70092.8 = 394.3999999999942
jkg = 537.1999999999971 - 394.3999999999942 = 142.8000000000029
rjkg = 142.8000000000029 / (20 - 4) = 8.925000000000182
f_hitung = 131.46666666666474 / 8.925000000000182 = 14.730158730158214


14.730158730158214

In [13]:
soal_2_df = pd.read_csv("https://raw.githubusercontent.com/notnsas/cautious-eureka/refs/heads/main/dataset/konbert-output-6cd3fae5.csv")
soal_2_df

ASTRA  BCA  CITI  AMEX
0      8   12    19  13.0
1      7   11    20  12.0
2     10   16    15  14.0
3     12   10    18  15.0
4     11   12    19   NaN

In [14]:
np.nansum(soal_2_df.to_numpy())**2

np.float64(64516.0)

In [15]:
np.count_nonzero(~np.isnan(data))

NameError: name 'data' is not defined

In [23]:
soal_2 = AnovaOneWay(soal_2_df)
soal_2.f_hitung()

jkp = 3590.2 - 3395.5789473684213 = 194.62105263157855
jkp : 194.62105263157855
k : 194.62105263157855
rjkp = 194.62105263157855 / (4 - 1) = 64.87368421052618
jkt = 3648.0 - 3395.5789473684213 = 252.42105263157873
jkp = 3590.2 - 3395.5789473684213 = 194.62105263157855
jkt = 3648.0 - 3395.5789473684213 = 252.42105263157873
jkp = 3590.2 - 3395.5789473684213 = 194.62105263157855
jkg = 252.42105263157873 - 194.62105263157855 = 57.80000000000018
rjkg = 57.80000000000018 / (19 - 4) = 3.8533333333333455
f_hitung = 64.87368421052618 / 3.8533333333333455 = 16.835731196503282


np.float64(16.835731196503282)

In [ ]:
soal_2.df_1

3

In [ ]:
a = df.to_numpy()
a

array([[63, 56, 56, 53],
       [66, 60, 60, 55],
       [63, 65, 57, 54],
       [62, 69, 54, 51],
       [65, 65, 58, 52]])

In [ ]:
np.nansum(a)

1184

In [ ]:
soal_3_df = pd.read_csv("/content/konbert-output-b43a9c7a.csv")
soal_3_df

Ceramah  Diskusi  Praktek
0       25     17.0       26
1       11     16.0       20
2       16     18.0       17
3       26     20.0       26
4       32     10.0       43
5       25     14.0       46
6       30     19.0       35
7       17      NaN       34

In [ ]:
soal_3 = AnovaOneWay(soal_3_df)
print(f"df1 : {soal_3.df_1}")
print(f"df2 : {soal_3.df_2}")
soal_3.f_hitung()


df1 : 2
df2 : 20
jkp = 13623.196428571428 - 12285.375 = 1337.8214285714275
jkp : 1337.8214285714275
k : 1337.8214285714275
rjkp = 1337.8214285714275 / (4 - 1) = 445.94047619047586
jkt = 14829.0 - 12285.375 = 2543.625
jkp = 13623.196428571428 - 12285.375 = 1337.8214285714275
jkt = 14829.0 - 12285.375 = 2543.625
jkp = 13623.196428571428 - 12285.375 = 1337.8214285714275
jkg = 2543.625 - 1337.8214285714275 = 1205.8035714285725
rjkg = 1205.8035714285725 / (23 - 3) = 60.290178571428626
f_hitung = 445.94047619047586 / 60.290178571428626 = 7.396569171911626


7.396569171911626

In [ ]:
soal_3_df.shape[1]

3

In [ ]:
# Define the data
data = {
    "Tugas Belajar (A1)": [6, 8, 5, 7, 7, 6, 6, 8, 7, 6, 7, None],  # Add None to match length
    "Izin Belajar (A2)": [5, 6, 6, 7, 5, 5, 5, 6, 5, 6, 8, 7],
    "Umum (A3)": [6, 9, 8, 7, 8, 9, 6, 6, 9, 8, 6, 8]
}

# Convert to DataFrame
soal_4_df = pd.DataFrame(data)

# Display DataFrame
print(soal_4_df)

    Tugas Belajar (A1)  Izin Belajar (A2)  Umum (A3)
0                  6.0                  5          6
1                  8.0                  6          9
2                  5.0                  6          8
3                  7.0                  7          7
4                  7.0                  5          8
5                  6.0                  5          9
6                  6.0                  5          6
7                  8.0                  6          6
8                  7.0                  5          9
9                  6.0                  6          8
10                 7.0                  8          6
11                 NaN                  7          8


In [ ]:
soal_4 = AnovaOneWay(soal_4_df)
print(f"df1 : {soal_4.df_1}")
print(f"df2 : {soal_4.df_2}")
soal_4.f_hitung()


df1 : 2
df2 : 32
jkp = 1579.5378787878788 - 1521.0 = 58.53787878787875
jkp : 58.53787878787875
k : 58.53787878787875
rjkp = 58.53787878787875 / (4 - 1) = 19.512626262626252
jkt = 1616.0 - 1521.0 = 95.0
jkp = 1579.5378787878788 - 1521.0 = 58.53787878787875
jkt = 1616.0 - 1521.0 = 95.0
jkp = 1579.5378787878788 - 1521.0 = 58.53787878787875
jkg = 95.0 - 58.53787878787875 = 36.46212121212125
rjkg = 36.46212121212125 / (35 - 3) = 1.139441287878789
f_hitung = 19.512626262626252 / 1.139441287878789 = 17.124731629614214


17.124731629614214

In [ ]:
soal_5_df = pd.read_csv("/content/konbert-output-505ee0e7.csv")
soal_5_df

Mesin 1  Mesin 2  Mesin 3  Mesin 4
0       20       30       60       50
1       30       40       80       50
2       10       30       70       50
3       30       50       40       30
4       10        0      100       20

In [ ]:
soal_5 = AnovaOneWay(soal_5_df)
print(f"df1 : {soal_5.df_1}")
print(f"df2 : {soal_5.df_2}")
soal_5.f_hitung()


df1 : 3
df2 : 16
jkp = 39000.0 - 32000.0 = 7000.0
jkp : 7000.0
k : 7000.0
rjkp = 7000.0 / (4 - 1) = 2333.3333333333335
jkt = 43600 - 32000.0 = 11600.0
jkp = 39000.0 - 32000.0 = 7000.0
jkt = 43600 - 32000.0 = 11600.0
jkp = 39000.0 - 32000.0 = 7000.0
jkg = 11600.0 - 7000.0 = 4600.0
rjkg = 4600.0 / (20 - 4) = 287.5
f_hitung = 2333.3333333333335 / 287.5 = 8.115942028985508


8.115942028985508